# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-22 16:18
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': '品牌', 'verbose_name_plural': '品牌'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.AlterField(
            model_name='product',
            name='image_back',
            field=versatileimagefield.fields.VersatileImageField(null=True, upload_to='product/%Y/%m', verbose_name='背部图片'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_right',
            field=versatileimagefield.fields.VersatileImageField(null=True, upload_to='product/%Y/%m', verbose_name='侧面图片'),
        ),
    ]
